import { Background } from './Background';
export const LoaderConfig = {
    frame : require("/src/sprites/SlotMachine_3x5.png"),
    spinBtn  : require("/src/sprites/ButtonSpin_1.png"),
    spinBtnOnPressed : require("/src/sprites/ButtonSpinHover_1.png"),
    maxBetBtn : require("../sprites/ButtonMaxBet_1.png"),
    maxBetBtOnPressed : require("../sprites/ButtonMaxBetHover_1.png"),
    autoSpin : require("../sprites/ButtonAutoSpin_1.png"),
    autoSpinOnPressed : require("../sprites/ButtonAutoSpinHover_1.png"),
    BetPanel : require("../sprites/PanelTotalBet.png"),
    pBtn  : require("../sprites/ButtonPlus.png"),
    mBtn  : require("../sprites/ButtonMinus.png"),
    pBtnH  : require("../sprites/ButtonPlusHover.png"),
    mBtnH  : require("../sprites/ButtonMinusHover.png"),
    lines : require("../sprites/PanelLines.png"),
    winPanel : require("../sprites/PanelWin.png"),
    balancePanel : require("../sprites/PanelBalance.png"),
    fireVase : require("../sprites/Vase.png"),
    PanelJackpot : require("../sprites/PanelJackpot.png"),
    MenuBtn : require("../sprites/ButtonMenu.png"),
    MenuBtnH : require("../sprites/ButtonMenuHover.png"),
    settingBtn : require("../sprites/ButtonSettings.png"),
    settingBtnH : require("../sprites/ButtonSettingsHover.png"),
    infoBtn : require("../sprites/ButtonInfo.png"),
    infoBtnH : require("../sprites/ButtonInfoHover.png"),
    rulesBtn : require("../sprites/ButtonRules.png"),
    rulesBtnH : require("../sprites/ButtonRulesHover.png"),
    
    slots0_0 : require("../sprites/Symbols/A/A (1).png"),
    slots0_1 : require("../sprites/Symbols/A/A (2).png"),
    slots0_2 : require("../sprites/Symbols/A/A (3).png"),
    slots0_3 : require("../sprites/Symbols/A/A (4).png"),
    slots0_4 : require("../sprites/Symbols/A/A (5).png"),
    slots0_5 : require("../sprites/Symbols/A/A (6).png"),
    slots0_6 : require("../sprites/Symbols/A/A (7).png"),
    slots0_7 : require("../sprites/Symbols/A/A (8).png"),
    slots0_8 : require("../sprites/Symbols/A/A (9).png"),
    slots0_9 : require("../sprites/Symbols/A/A (10).png"),
    slots0_10: require("../sprites/Symbols/A/A (11).png"),
    slots0_11: require("../sprites/Symbols/A/A (12).png"),
    slots0_12: require("../sprites/Symbols/A/A (13).png"),
    slots0_13: require("../sprites/Symbols/A/A (14).png"),
    slots0_14: require("../sprites/Symbols/A/A (15).png"),
    slots0_15: require("../sprites/Symbols/A/A (16).png"),
    slots0_16: require("../sprites/Symbols/A/A (17).png"),
    slots0_17: require("../sprites/Symbols/A/A (18).png"),
    slots0_18: require("../sprites/Symbols/A/A (19).png"),
    slots0_19: require("../sprites/Symbols/A/A (20).png"),
    slots0_20: require("../sprites/Symbols/A/A (21).png"),
    slots0_21: require("../sprites/Symbols/A/A (22).png"),
    slots0_22: require("../sprites/Symbols/A/A (23).png"),
    slots0_23: require("../sprites/Symbols/A/A (24).png"),

    slots1_0 : require("../sprites/Symbols/K/K (1).png"),
    slots1_1 : require("../sprites/Symbols/K/K (2).png"),
    slots1_2 : require("../sprites/Symbols/K/K (3).png"),
    slots1_3 : require("../sprites/Symbols/K/K (4).png"),
    slots1_4 : require("../sprites/Symbols/K/K (5).png"),
    slots1_5 : require("../sprites/Symbols/K/K (6).png"),
    slots1_6 : require("../sprites/Symbols/K/K (7).png"),
    slots1_7 : require("../sprites/Symbols/K/K (8).png"),
    slots1_8 : require("../sprites/Symbols/K/K (9).png"),
    slots1_9 : require("../sprites/Symbols/K/K (10).png"),
    slots1_10: require("../sprites/Symbols/K/K (11).png"),
    slots1_11: require("../sprites/Symbols/K/K (12).png"),
    slots1_12: require("../sprites/Symbols/K/K (13).png"),
    slots1_13: require("../sprites/Symbols/K/K (14).png"),
    slots1_14: require("../sprites/Symbols/K/K (15).png"),
    slots1_15: require("../sprites/Symbols/K/K (16).png"),
    slots1_16: require("../sprites/Symbols/K/K (17).png"),
    slots1_17: require("../sprites/Symbols/K/K (18).png"),
    slots1_18: require("../sprites/Symbols/K/K (19).png"),
    slots1_19: require("../sprites/Symbols/K/K (20).png"),
    slots1_20: require("../sprites/Symbols/K/K (21).png"),
    slots1_21: require("../sprites/Symbols/K/K (22).png"),
    slots1_22: require("../sprites/Symbols/K/K (23).png"),
    slots1_23: require("../sprites/Symbols/K/K (24).png"),

    slots2_0 : require("../sprites/Symbols/Q/Q (1).png"),
    slots2_1 : require("../sprites/Symbols/Q/Q (2).png"),
    slots2_2 : require("../sprites/Symbols/Q/Q (3).png"),
    slots2_3 : require("../sprites/Symbols/Q/Q (4).png"),
    slots2_4 : require("../sprites/Symbols/Q/Q (5).png"),
    slots2_5 : require("../sprites/Symbols/Q/Q (6).png"),
    slots2_6 : require("../sprites/Symbols/Q/Q (7).png"),
    slots2_7 : require("../sprites/Symbols/Q/Q (8).png"),
    slots2_8 : require("../sprites/Symbols/Q/Q (9).png"),
    slots2_9 : require("../sprites/Symbols/Q/Q (10).png"),
    slots2_10: require("../sprites/Symbols/Q/Q (11).png"),
    slots2_11: require("../sprites/Symbols/Q/Q (12).png"),
    slots2_12: require("../sprites/Symbols/Q/Q (13).png"),
    slots2_13: require("../sprites/Symbols/Q/Q (14).png"),
    slots2_14: require("../sprites/Symbols/Q/Q (15).png"),
    slots2_15: require("../sprites/Symbols/Q/Q (16).png"),
    slots2_16: require("../sprites/Symbols/Q/Q (17).png"),
    slots2_17: require("../sprites/Symbols/Q/Q (18).png"),
    slots2_18: require("../sprites/Symbols/Q/Q (19).png"),
    slots2_19: require("../sprites/Symbols/Q/Q (20).png"),
    slots2_20: require("../sprites/Symbols/Q/Q (21).png"),
    slots2_21: require("../sprites/Symbols/Q/Q (22).png"),
    slots2_22: require("../sprites/Symbols/Q/Q (23).png"),
    slots2_23: require("../sprites/Symbols/Q/Q (24).png"),
    
    slots3_0 : require("../sprites/Symbols/J/J (1).png"),
    slots3_1 : require("../sprites/Symbols/J/J (2).png"),
    slots3_2 : require("../sprites/Symbols/J/J (3).png"),
    slots3_3 : require("../sprites/Symbols/J/J (4).png"),
    slots3_4 : require("../sprites/Symbols/J/J (5).png"),
    slots3_5 : require("../sprites/Symbols/J/J (6).png"),
    slots3_6 : require("../sprites/Symbols/J/J (7).png"),
    slots3_7 : require("../sprites/Symbols/J/J (8).png"),
    slots3_8 : require("../sprites/Symbols/J/J (9).png"),
    slots3_9 : require("../sprites/Symbols/J/J (10).png"),
    slots3_10: require("../sprites/Symbols/J/J (11).png"),
    slots3_11: require("../sprites/Symbols/J/J (12).png"),
    slots3_12: require("../sprites/Symbols/J/J (13).png"),
    slots3_13: require("../sprites/Symbols/J/J (14).png"),
    slots3_14: require("../sprites/Symbols/J/J (15).png"),
    slots3_15: require("../sprites/Symbols/J/J (16).png"),
    slots3_16: require("../sprites/Symbols/J/J (17).png"),
    slots3_17: require("../sprites/Symbols/J/J (18).png"),
    slots3_18: require("../sprites/Symbols/J/J (19).png"),
    slots3_19: require("../sprites/Symbols/J/J (20).png"),
    slots3_20: require("../sprites/Symbols/J/J (21).png"),
    slots3_21: require("../sprites/Symbols/J/J (22).png"),
    slots3_22: require("../sprites/Symbols/J/J (23).png"),
    slots3_23: require("../sprites/Symbols/J/J (24).png"),

    slots4_0 : require("../sprites/Symbols/10/10 (1).png"),
    slots4_1 : require("../sprites/Symbols/10/10 (2).png"),
    slots4_2 : require("../sprites/Symbols/10/10 (3).png"),
    slots4_3 : require("../sprites/Symbols/10/10 (4).png"),
    slots4_4 : require("../sprites/Symbols/10/10 (5).png"),
    slots4_5 : require("../sprites/Symbols/10/10 (6).png"),
    slots4_6 : require("../sprites/Symbols/10/10 (7).png"),
    slots4_7 : require("../sprites/Symbols/10/10 (8).png"),
    slots4_8 : require("../sprites/Symbols/10/10 (9).png"),
    slots4_9 : require("../sprites/Symbols/10/10 (10).png"),
    slots4_10: require("../sprites/Symbols/10/10 (11).png"),
    slots4_11: require("../sprites/Symbols/10/10 (12).png"),
    slots4_12: require("../sprites/Symbols/10/10 (13).png"),
    slots4_13: require("../sprites/Symbols/10/10 (14).png"),
    slots4_14: require("../sprites/Symbols/10/10 (15).png"),
    slots4_15: require("../sprites/Symbols/10/10 (16).png"),
    slots4_16: require("../sprites/Symbols/10/10 (17).png"),
    slots4_17: require("../sprites/Symbols/10/10 (18).png"),
    slots4_18: require("../sprites/Symbols/10/10 (19).png"),
    slots4_19: require("../sprites/Symbols/10/10 (20).png"),
    slots4_20: require("../sprites/Symbols/10/10 (21).png"),
    slots4_21: require("../sprites/Symbols/10/10 (22).png"),
    slots4_22: require("../sprites/Symbols/10/10 (23).png"),
    slots4_23: require("../sprites/Symbols/10/10 (24).png"),

    slots5_0 : require("../sprites/Symbols/Eye/Eye (1).png"),
    slots5_1 : require("../sprites/Symbols/Eye/Eye (2).png"),
    slots5_2 : require("../sprites/Symbols/Eye/Eye (3).png"),
    slots5_3 : require("../sprites/Symbols/Eye/Eye (4).png"),
    slots5_4 : require("../sprites/Symbols/Eye/Eye (5).png"),
    slots5_5 : require("../sprites/Symbols/Eye/Eye (6).png"),
    slots5_6 : require("../sprites/Symbols/Eye/Eye (7).png"),
    slots5_7 : require("../sprites/Symbols/Eye/Eye (8).png"),
    slots5_8 : require("../sprites/Symbols/Eye/Eye (9).png"),
    slots5_9 : require("../sprites/Symbols/Eye/Eye (10).png"),
    slots5_10: require("../sprites/Symbols/Eye/Eye (11).png"),
    slots5_11: require("../sprites/Symbols/Eye/Eye (12).png"),
    slots5_12: require("../sprites/Symbols/Eye/Eye (13).png"),
    slots5_13: require("../sprites/Symbols/Eye/Eye (14).png"),
    slots5_14: require("../sprites/Symbols/Eye/Eye (15).png"),
    slots5_15: require("../sprites/Symbols/Eye/Eye (16).png"),
    slots5_16: require("../sprites/Symbols/Eye/Eye (17).png"),
    slots5_17: require("../sprites/Symbols/Eye/Eye (18).png"),
    slots5_18: require("../sprites/Symbols/Eye/Eye (19).png"),
    slots5_19: require("../sprites/Symbols/Eye/Eye (20).png"),
    slots5_20: require("../sprites/Symbols/Eye/Eye (21).png"),
    slots5_21: require("../sprites/Symbols/Eye/Eye (22).png"),
    slots5_22: require("../sprites/Symbols/Eye/Eye (23).png"),
    slots5_23: require("../sprites/Symbols/Eye/Eye (24).png"),

    slots6_0 : require("../sprites/Symbols/Lotus/Lotus (1).png"),
    slots6_1 : require("../sprites/Symbols/Lotus/Lotus (2).png"),
    slots6_2 : require("../sprites/Symbols/Lotus/Lotus (3).png"),
    slots6_3 : require("../sprites/Symbols/Lotus/Lotus (4).png"),
    slots6_4 : require("../sprites/Symbols/Lotus/Lotus (5).png"),
    slots6_5 : require("../sprites/Symbols/Lotus/Lotus (6).png"),
    slots6_6 : require("../sprites/Symbols/Lotus/Lotus (7).png"),
    slots6_7 : require("../sprites/Symbols/Lotus/Lotus (8).png"),
    slots6_8 : require("../sprites/Symbols/Lotus/Lotus (9).png"),
    slots6_9 : require("../sprites/Symbols/Lotus/Lotus (10).png"),
    slots6_10: require("../sprites/Symbols/Lotus/Lotus (11).png"),
    slots6_11: require("../sprites/Symbols/Lotus/Lotus (12).png"),
    slots6_12: require("../sprites/Symbols/Lotus/Lotus (13).png"),
    slots6_13: require("../sprites/Symbols/Lotus/Lotus (14).png"),
    slots6_14: require("../sprites/Symbols/Lotus/Lotus (15).png"),
    slots6_15: require("../sprites/Symbols/Lotus/Lotus (16).png"),
    slots6_16: require("../sprites/Symbols/Lotus/Lotus (17).png"),
    slots6_17: require("../sprites/Symbols/Lotus/Lotus (18).png"),
    slots6_18: require("../sprites/Symbols/Lotus/Lotus (19).png"),
    slots6_19: require("../sprites/Symbols/Lotus/Lotus (20).png"),
    slots6_20: require("../sprites/Symbols/Lotus/Lotus (21).png"),
    slots6_21: require("../sprites/Symbols/Lotus/Lotus (22).png"),
    slots6_22: require("../sprites/Symbols/Lotus/Lotus (23).png"),
    slots6_23: require("../sprites/Symbols/Lotus/Lotus (24).png"),

    slots7_0 : require("../sprites/Symbols/Shen/Shen (1).png"),
    slots7_1 : require("../sprites/Symbols/Shen/Shen (2).png"),
    slots7_2 : require("../sprites/Symbols/Shen/Shen (3).png"),
    slots7_3 : require("../sprites/Symbols/Shen/Shen (4).png"),
    slots7_4 : require("../sprites/Symbols/Shen/Shen (5).png"),
    slots7_5 : require("../sprites/Symbols/Shen/Shen (6).png"),
    slots7_6 : require("../sprites/Symbols/Shen/Shen (7).png"),
    slots7_7 : require("../sprites/Symbols/Shen/Shen (8).png"),
    slots7_8 : require("../sprites/Symbols/Shen/Shen (9).png"),
    slots7_9 : require("../sprites/Symbols/Shen/Shen (10).png"),
    slots7_10: require("../sprites/Symbols/Shen/Shen (11).png"),
    slots7_11: require("../sprites/Symbols/Shen/Shen (12).png"),
    slots7_12: require("../sprites/Symbols/Shen/Shen (13).png"),
    slots7_13: require("../sprites/Symbols/Shen/Shen (14).png"),
    slots7_14: require("../sprites/Symbols/Shen/Shen (15).png"),
    slots7_15: require("../sprites/Symbols/Shen/Shen (16).png"),
    slots7_16: require("../sprites/Symbols/Shen/Shen (17).png"),
    slots7_17: require("../sprites/Symbols/Shen/Shen (18).png"),
    slots7_18: require("../sprites/Symbols/Shen/Shen (19).png"),
    slots7_19: require("../sprites/Symbols/Shen/Shen (20).png"),
    slots7_20: require("../sprites/Symbols/Shen/Shen (21).png"),
    slots7_21: require("../sprites/Symbols/Shen/Shen (22).png"),
    slots7_22: require("../sprites/Symbols/Shen/Shen (23).png"),
    slots7_23: require("../sprites/Symbols/Shen/Shen (24).png"),

    slots8_0 : require("../sprites/Symbols/Ankh/Ankh (1).png"),
    slots8_1 : require("../sprites/Symbols/Ankh/Ankh (2).png"),
    slots8_2 : require("../sprites/Symbols/Ankh/Ankh (3).png"),
    slots8_3 : require("../sprites/Symbols/Ankh/Ankh (4).png"),
    slots8_4 : require("../sprites/Symbols/Ankh/Ankh (5).png"),
    slots8_5 : require("../sprites/Symbols/Ankh/Ankh (6).png"),
    slots8_6 : require("../sprites/Symbols/Ankh/Ankh (7).png"),
    slots8_7 : require("../sprites/Symbols/Ankh/Ankh (8).png"),
    slots8_8 : require("../sprites/Symbols/Ankh/Ankh (9).png"),
    slots8_9 : require("../sprites/Symbols/Ankh/Ankh (10).png"),
    slots8_10: require("../sprites/Symbols/Ankh/Ankh (11).png"),
    slots8_11: require("../sprites/Symbols/Ankh/Ankh (12).png"),
    slots8_12: require("../sprites/Symbols/Ankh/Ankh (13).png"),
    slots8_13: require("../sprites/Symbols/Ankh/Ankh (14).png"),
    slots8_14: require("../sprites/Symbols/Ankh/Ankh (15).png"),
    slots8_15: require("../sprites/Symbols/Ankh/Ankh (16).png"),
    slots8_16: require("../sprites/Symbols/Ankh/Ankh (17).png"),
    slots8_17: require("../sprites/Symbols/Ankh/Ankh (18).png"),
    slots8_18: require("../sprites/Symbols/Ankh/Ankh (19).png"),
    slots8_19: require("../sprites/Symbols/Ankh/Ankh (20).png"),
    slots8_20: require("../sprites/Symbols/Ankh/Ankh (21).png"),
    slots8_21: require("../sprites/Symbols/Ankh/Ankh (22).png"),
    slots8_22: require("../sprites/Symbols/Ankh/Ankh (23).png"),
    slots8_23: require("../sprites/Symbols/Ankh/Ankh (24).png"),

    slots9_0 : require("../sprites/Symbols/Wick/Wick (1).png"),
    slots9_1 : require("../sprites/Symbols/Wick/Wick (2).png"),
    slots9_2 : require("../sprites/Symbols/Wick/Wick (3).png"),
    slots9_3 : require("../sprites/Symbols/Wick/Wick (4).png"),
    slots9_4 : require("../sprites/Symbols/Wick/Wick (5).png"),
    slots9_5 : require("../sprites/Symbols/Wick/Wick (6).png"),
    slots9_6 : require("../sprites/Symbols/Wick/Wick (7).png"),
    slots9_7 : require("../sprites/Symbols/Wick/Wick (8).png"),
    slots9_8 : require("../sprites/Symbols/Wick/Wick (9).png"),
    slots9_9 : require("../sprites/Symbols/Wick/Wick (10).png"),
    slots9_10: require("../sprites/Symbols/Wick/Wick (11).png"),
    slots9_11: require("../sprites/Symbols/Wick/Wick (12).png"),
    slots9_12: require("../sprites/Symbols/Wick/Wick (13).png"),
    slots9_13: require("../sprites/Symbols/Wick/Wick (14).png"),
    slots9_14: require("../sprites/Symbols/Wick/Wick (15).png"),
    slots9_15: require("../sprites/Symbols/Wick/Wick (16).png"),
    slots9_16: require("../sprites/Symbols/Wick/Wick (17).png"),
    slots9_17: require("../sprites/Symbols/Wick/Wick (18).png"),
    slots9_18: require("../sprites/Symbols/Wick/Wick (19).png"),
    slots9_19: require("../sprites/Symbols/Wick/Wick (20).png"),
    slots9_20: require("../sprites/Symbols/Wick/Wick (21).png"),
    slots9_21: require("../sprites/Symbols/Wick/Wick (22).png"),
    slots9_22: require("../sprites/Symbols/Wick/Wick (23).png"),
    slots9_23: require("../sprites/Symbols/Wick/Wick (24).png"),

    slots10_0 : require("../sprites/Symbols/Scatter/Scatter (1).png"),
    slots10_1 : require("../sprites/Symbols/Scatter/Scatter (2).png"),
    slots10_2 : require("../sprites/Symbols/Scatter/Scatter (3).png"),
    slots10_3 : require("../sprites/Symbols/Scatter/Scatter (4).png"),
    slots10_4 : require("../sprites/Symbols/Scatter/Scatter (5).png"),
    slots10_5 : require("../sprites/Symbols/Scatter/Scatter (6).png"),
    slots10_6 : require("../sprites/Symbols/Scatter/Scatter (7).png"),
    slots10_7 : require("../sprites/Symbols/Scatter/Scatter (8).png"),
    slots10_8 : require("../sprites/Symbols/Scatter/Scatter (9).png"),
    slots10_9 : require("../sprites/Symbols/Scatter/Scatter (10).png"),
    slots10_10: require("../sprites/Symbols/Scatter/Scatter (11).png"),
    slots10_11: require("../sprites/Symbols/Scatter/Scatter (12).png"),
    slots10_12: require("../sprites/Symbols/Scatter/Scatter (13).png"),
    slots10_13: require("../sprites/Symbols/Scatter/Scatter (14).png"),
    slots10_14: require("../sprites/Symbols/Scatter/Scatter (15).png"),
    slots10_15: require("../sprites/Symbols/Scatter/Scatter (16).png"),
    slots10_16: require("../sprites/Symbols/Scatter/Scatter (17).png"),
    slots10_17: require("../sprites/Symbols/Scatter/Scatter (18).png"),
    slots10_18: require("../sprites/Symbols/Scatter/Scatter (19).png"),
    slots10_19: require("../sprites/Symbols/Scatter/Scatter (20).png"),
    slots10_20: require("../sprites/Symbols/Scatter/Scatter (21).png"),
    slots10_21: require("../sprites/Symbols/Scatter/Scatter (22).png"),
    slots10_22: require("../sprites/Symbols/Scatter/Scatter (23).png"),
    slots10_23: require("../sprites/Symbols/Scatter/Scatter (24).png"),

    slots11_0 : require("../sprites/Symbols/FreeSpins/FreeSpins (1).png"),
    slots11_1 : require("../sprites/Symbols/FreeSpins/FreeSpins (2).png"),
    slots11_2 : require("../sprites/Symbols/FreeSpins/FreeSpins (3).png"),
    slots11_3 : require("../sprites/Symbols/FreeSpins/FreeSpins (4).png"),
    slots11_4 : require("../sprites/Symbols/FreeSpins/FreeSpins (5).png"),
    slots11_5 : require("../sprites/Symbols/FreeSpins/FreeSpins (6).png"),
    slots11_6 : require("../sprites/Symbols/FreeSpins/FreeSpins (7).png"),
    slots11_7 : require("../sprites/Symbols/FreeSpins/FreeSpins (8).png"),
    slots11_8 : require("../sprites/Symbols/FreeSpins/FreeSpins (9).png"),
    slots11_9 : require("../sprites/Symbols/FreeSpins/FreeSpins (10).png"),
    slots11_10: require("../sprites/Symbols/FreeSpins/FreeSpins (11).png"),
    slots11_11: require("../sprites/Symbols/FreeSpins/FreeSpins (12).png"),
    slots11_12: require("../sprites/Symbols/FreeSpins/FreeSpins (13).png"),
    slots11_13: require("../sprites/Symbols/FreeSpins/FreeSpins (14).png"),
    slots11_14: require("../sprites/Symbols/FreeSpins/FreeSpins (15).png"),
    slots11_15: require("../sprites/Symbols/FreeSpins/FreeSpins (16).png"),
    slots11_16: require("../sprites/Symbols/FreeSpins/FreeSpins (17).png"),
    slots11_17: require("../sprites/Symbols/FreeSpins/FreeSpins (18).png"),
    slots11_18: require("../sprites/Symbols/FreeSpins/FreeSpins (19).png"),
    slots11_19: require("../sprites/Symbols/FreeSpins/FreeSpins (20).png"),
    slots11_20: require("../sprites/Symbols/FreeSpins/FreeSpins (21).png"),
    slots11_21: require("../sprites/Symbols/FreeSpins/FreeSpins (22).png"),
    slots11_22: require("../sprites/Symbols/FreeSpins/FreeSpins (23).png"),
    slots11_23: require("../sprites/Symbols/FreeSpins/FreeSpins (24).png"),

    slots12_0 : require("../sprites/Symbols/Bonus/Bonus (1).png"),
    slots12_1 : require("../sprites/Symbols/Bonus/Bonus (2).png"),
    slots12_2 : require("../sprites/Symbols/Bonus/Bonus (3).png"),
    slots12_3 : require("../sprites/Symbols/Bonus/Bonus (4).png"),
    slots12_4 : require("../sprites/Symbols/Bonus/Bonus (5).png"),
    slots12_5 : require("../sprites/Symbols/Bonus/Bonus (6).png"),
    slots12_6 : require("../sprites/Symbols/Bonus/Bonus (7).png"),
    slots12_7 : require("../sprites/Symbols/Bonus/Bonus (8).png"),
    slots12_8 : require("../sprites/Symbols/Bonus/Bonus (9).png"),
    slots12_9 : require("../sprites/Symbols/Bonus/Bonus (10).png"),
    slots12_10: require("../sprites/Symbols/Bonus/Bonus (11).png"),
    slots12_11: require("../sprites/Symbols/Bonus/Bonus (12).png"),
    slots12_12: require("../sprites/Symbols/Bonus/Bonus (13).png"),
    slots12_13: require("../sprites/Symbols/Bonus/Bonus (14).png"),
    slots12_14: require("../sprites/Symbols/Bonus/Bonus (15).png"),
    slots12_15: require("../sprites/Symbols/Bonus/Bonus (16).png"),
    slots12_16: require("../sprites/Symbols/Bonus/Bonus (17).png"),
    slots12_17: require("../sprites/Symbols/Bonus/Bonus (18).png"),
    slots12_18: require("../sprites/Symbols/Bonus/Bonus (19).png"),
    slots12_19: require("../sprites/Symbols/Bonus/Bonus (20).png"),
    slots12_20: require("../sprites/Symbols/Bonus/Bonus (21).png"),
    slots12_21: require("../sprites/Symbols/Bonus/Bonus (22).png"),
    slots12_22: require("../sprites/Symbols/Bonus/Bonus (23).png"),
    slots12_23: require("../sprites/Symbols/Bonus/Bonus (24).png"),

    slots13_0 : require("../sprites/Symbols/Wild/Wild (1).png"),
    slots13_1 : require("../sprites/Symbols/Wild/Wild (2).png"),
    slots13_2 : require("../sprites/Symbols/Wild/Wild (3).png"),
    slots13_3 : require("../sprites/Symbols/Wild/Wild (4).png"),
    slots13_4 : require("../sprites/Symbols/Wild/Wild (5).png"),
    slots13_5 : require("../sprites/Symbols/Wild/Wild (6).png"),
    slots13_6 : require("../sprites/Symbols/Wild/Wild (7).png"),
    slots13_7 : require("../sprites/Symbols/Wild/Wild (8).png"),
    slots13_8 : require("../sprites/Symbols/Wild/Wild (9).png"),
    slots13_9 : require("../sprites/Symbols/Wild/Wild (10).png"),
    slots13_10: require("../sprites/Symbols/Wild/Wild (11).png"),
    slots13_11: require("../sprites/Symbols/Wild/Wild (12).png"),
    slots13_12: require("../sprites/Symbols/Wild/Wild (13).png"),
    slots13_13: require("../sprites/Symbols/Wild/Wild (14).png"),
    slots13_14: require("../sprites/Symbols/Wild/Wild (15).png"),
    slots13_15: require("../sprites/Symbols/Wild/Wild (16).png"),
    slots13_16: require("../sprites/Symbols/Wild/Wild (17).png"),
    slots13_17: require("../sprites/Symbols/Wild/Wild (18).png"),
    slots13_18: require("../sprites/Symbols/Wild/Wild (19).png"),
    slots13_19: require("../sprites/Symbols/Wild/Wild (20).png"),
    slots13_20: require("../sprites/Symbols/Wild/Wild (21).png"),
    slots13_21: require("../sprites/Symbols/Wild/Wild (22).png"),
    slots13_22: require("../sprites/Symbols/Wild/Wild (23).png"),
    slots13_23: require("../sprites/Symbols/Wild/Wild (24).png"),


    slots14_0 : require("../sprites/Symbols/Jackpot/Jackpot (1).png"),
    slots14_1 : require("../sprites/Symbols/Jackpot/Jackpot (2).png"),
    slots14_2 : require("../sprites/Symbols/Jackpot/Jackpot (3).png"),
    slots14_3 : require("../sprites/Symbols/Jackpot/Jackpot (4).png"),
    slots14_4 : require("../sprites/Symbols/Jackpot/Jackpot (5).png"),
    slots14_5 : require("../sprites/Symbols/Jackpot/Jackpot (6).png"),
    slots14_6 : require("../sprites/Symbols/Jackpot/Jackpot (7).png"),
    slots14_7 : require("../sprites/Symbols/Jackpot/Jackpot (8).png"),
    slots14_8 : require("../sprites/Symbols/Jackpot/Jackpot (9).png"),
    slots14_9 : require("../sprites/Symbols/Jackpot/Jackpot (10).png"),
    slots14_10: require("../sprites/Symbols/Jackpot/Jackpot (11).png"),
    slots14_11: require("../sprites/Symbols/Jackpot/Jackpot (12).png"),
    slots14_12: require("../sprites/Symbols/Jackpot/Jackpot (13).png"),
    slots14_13: require("../sprites/Symbols/Jackpot/Jackpot (14).png"),
    slots14_14: require("../sprites/Symbols/Jackpot/Jackpot (15).png"),
    slots14_15: require("../sprites/Symbols/Jackpot/Jackpot (16).png"),
    slots14_16: require("../sprites/Symbols/Jackpot/Jackpot (17).png"),
    slots14_17: require("../sprites/Symbols/Jackpot/Jackpot (18).png"),
    slots14_18: require("../sprites/Symbols/Jackpot/Jackpot (19).png"),
    slots14_19: require("../sprites/Symbols/Jackpot/Jackpot (20).png"),
    slots14_20: require("../sprites/Symbols/Jackpot/Jackpot (21).png"),
    slots14_21: require("../sprites/Symbols/Jackpot/Jackpot (22).png"),
    slots14_22: require("../sprites/Symbols/Jackpot/Jackpot (23).png"),
    slots14_23: require("../sprites/Symbols/Jackpot/Jackpot (24).png"),

    fire_1 : require("../sprites/fire/Fire (1).png"),
    fire_2 : require("../sprites/fire/Fire (2).png"),
    fire_3 : require("../sprites/fire/Fire (3).png"),
    fire_4 : require("../sprites/fire/Fire (4).png"),
    fire_5 : require("../sprites/fire/Fire (5).png"),
    fire_6 : require("../sprites/fire/Fire (6).png"),
    fire_7 : require("../sprites/fire/Fire (7).png"),
    fire_8 : require("../sprites/fire/Fire (8).png"),
    fire_9 : require("../sprites/fire/Fire (9).png"),
    fire_10: require("../sprites/fire/Fire (10).png"),
    fire_11: require("../sprites/fire/Fire (11).png"),
    fire_12: require("../sprites/fire/Fire (12).png"),
    fire_13: require("../sprites/fire/Fire (13).png"),
    fire_14: require("../sprites/fire/Fire (14).png"),
    fire_15: require("../sprites/fire/Fire (15).png"),
    fire_16: require("../sprites/fire/Fire (16).png"),
    fire_17: require("../sprites/fire/Fire (17).png"),
    fire_18: require("../sprites/fire/Fire (18).png"),
    fire_19: require("../sprites/fire/Fire (19).png"),
    fire_20: require("../sprites/fire/Fire (20).png"),
    fire_21: require("../sprites/fire/Fire (21).png"),
    fire_22: require("../sprites/fire/Fire (22).png"),
    fire_23: require("../sprites/fire/Fire (23).png"),
    
}

export const staticData = {
    // logoURL: "https://cccdn.b-cdn.net/1584464368856.png",
    // logoURL: require("/static/logo.png").default,
    Background: require("/static/Background.png").default,
};

export const fontData = ["Montserrat"];



export const LoaderSoundConfig: any = {
onSpin : require("../sounds/onStartCoin.mp3"),
};

export const preloaderConfig = {
    // startLogo: require("../sprites/Logo.png")
}